# Common stuff for all servers

- name: setup NTP
  yum: pkg=ntp state=latest

- name: enable ntp on boot
  shell: chkconfig ntpd on

- name: template ntp config file
  template: src=ntp.j2 dest=/etc/ntp.conf

- name: start NTPD service
  service: name=ntpd state=restarted

- name: Setup mysql-python
  yum: pkg={{ item }} state=latest
  with_items:
  - MySQL-python
  - python-pip
  - mysql
